FROM node:20-alpine AS build

WORKDIR /client

COPY package*.json .

RUN npm i --force

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /client/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]
