export const charts = {
  Rock: "Rock",
  Rap: "Hip Hop/R&B",
  Hot: "Hot-100",
  Alt: "Alternative",
  Pop: "Pop",
  Country: "Country",
  Latin: "Latin",
};

export const chartDates = {
  Rock: "1981-03-22",
  Rap: "1958-10-20",
  Hot: "1958-08-04",
  Alt: "1988-09-05",
  Pop: "1961-07-17",
  Country: "1958-10-20",
  Latin: "1986-09-15",
};

export const chartInfo = {
  Rock: {
    name: "Rock",
    firstChart: "March 21, 1981",
    info: "The week's most popular mainstream rock songs ranked by radio airplay.",
    link: "https://www.billboard.com/charts/hot-mainstream-rock-tracks/",
  },
  Rap: {
    name: "Hip Hop/R&B",
    firstChart: "October 20, 1958",
    info: "The week's most popular R&B/Hip Hop songs ranked by streaming and radio airplay.",
    link: "https://www.billboard.com/charts/r-b-hip-hop-songs/",
  },
  Hot: {
    name: "Billboard Hot-100",
    firstChart: "August 4, 1958",
    info: "The week's most popular songs from all genres ranked by streaming and radio airplay.",
    link: "https://www.billboard.com/charts/hot-100/",
  },
  Alt: {
    name: "Alternative",
    firstChart: "September 10, 1988",
    info: "The week's most popular alternative songs ranked by radio airplay.",
    link: "https://www.billboard.com/charts/alternative-airplay/",
  },
  Pop: {
    name: "Adult Contemporary",
    firstChart: "July 17, 1961",
    info: "The week's most popular adult pop songs ranked by radio airplay.",
    link: "https://www.billboard.com/charts/adult-contemporary/",
  },
  Country: {
    name: "Country",
    firstChart: "October 20, 1958",
    info: "The week's most popular country songs ranked by streaming and radio airplay.",
    link: "https://www.billboard.com/charts/country-songs/",
  },
  Latin: {
    name: "Latin",
    firstChart: "September 20, 1986",
    info: "The week's most popular latin songs ranked by streaming and radio airplay.",
    link: "https://www.billboard.com/charts/latin-songs/",
  },
};

export const testArtistData = {
  songs: [
    {
      title: "Say Say Say",
      artist: "Paul McCartney And Michael Jackson",
      debutDate: "1983-10-15",
      peak: 1,
      peakDate: "1983-12-10",
      weeksOn: 22,
    },
    {
      title: "Coming Up (Live At Glasgow)",
      artist: "Paul McCartney And Wings",
      debutDate: "1980-04-26",
      peak: 1,
      peakDate: "1980-06-28",
      weeksOn: 21,
    },
    {
      title: "Ebony And Ivory",
      artist: "Paul McCartney And Stevie Wonder",
      debutDate: "1982-04-10",
      peak: 1,
      peakDate: "1982-05-15",
      weeksOn: 19,
    },
    {
      title: "Silly Love Songs",
      artist: "Wings",
      debutDate: "1976-04-10",
      peak: 1,
      peakDate: "1976-05-22",
      weeksOn: 19,
    },
    {
      title: "With A Little Luck",
      artist: "Wings",
      debutDate: "1978-03-25",
      peak: 1,
      peakDate: "1978-05-20",
      weeksOn: 18,
    },
    {
      title: "My Love",
      artist: "Paul McCartney And Wings",
      debutDate: "1973-04-14",
      peak: 1,
      peakDate: "1973-06-02",
      weeksOn: 18,
    },
    {
      title: "Band On The Run",
      artist: "Paul McCartney And Wings",
      debutDate: "1974-04-20",
      peak: 1,
      peakDate: "1974-06-08",
      weeksOn: 18,
    },
    {
      title: "Listen To What The Man Said",
      artist: "Wings",
      debutDate: "1975-05-31",
      peak: 1,
      peakDate: "1975-07-19",
      weeksOn: 14,
    },
    {
      title: "Uncle Albert/Admiral Halsey",
      artist: "Paul & Linda McCartney",
      debutDate: "1971-08-14",
      peak: 1,
      peakDate: "1971-09-04",
      weeksOn: 13,
    },
    {
      title: "The Girl Is Mine",
      artist: "Michael Jackson And Paul McCartney",
      debutDate: "1982-11-06",
      peak: 2,
      peakDate: "1983-01-08",
      weeksOn: 18,
    },
    {
      title: "Live And Let Die",
      artist: "Wings",
      debutDate: "1973-07-07",
      peak: 2,
      peakDate: "1973-08-11",
      weeksOn: 14,
    },
    {
      title: "Junior's Farm/Sally G",
      artist: "Paul McCartney And Wings",
      debutDate: "1974-11-09",
      peak: 3,
      peakDate: "1975-01-11",
      weeksOn: 17,
    },
    {
      title: "Let 'em In",
      artist: "Wings",
      debutDate: "1976-07-04",
      peak: 3,
      peakDate: "1976-08-14",
      weeksOn: 16,
    },
    {
      title: "FourFiveSeconds",
      artist: "Rihanna & Kanye West & Paul McCartney",
      debutDate: "2015-02-07",
      peak: 4,
      peakDate: "2015-02-28",
      weeksOn: 20,
    },
    {
      title: "Goodnight Tonight",
      artist: "Wings",
      debutDate: "1979-03-31",
      peak: 5,
      peakDate: "1979-05-19",
      weeksOn: 16,
    },
    {
      title: "Another Day/Oh Woman Oh Why",
      artist: "Paul McCartney",
      debutDate: "1971-03-06",
      peak: 5,
      peakDate: "1971-04-17",
      weeksOn: 12,
    },
    {
      title: "No More Lonely Nights",
      artist: "Paul McCartney",
      debutDate: "1984-10-13",
      peak: 6,
      peakDate: "1984-12-08",
      weeksOn: 18,
    },
    {
      title: "Spies Like Us",
      artist: "Paul McCartney",
      debutDate: "1985-11-23",
      peak: 7,
      peakDate: "1986-02-08",
      weeksOn: 17,
    },
    {
      title: "Jet",
      artist: "Paul McCartney And Wings",
      debutDate: "1974-02-09",
      peak: 7,
      peakDate: "1974-03-30",
      weeksOn: 14,
    },
    {
      title: "Take It Away",
      artist: "Paul McCartney",
      debutDate: "1982-07-10",
      peak: 10,
      peakDate: "1982-08-21",
      weeksOn: 16,
    },
    {
      title: "Maybe I'm Amazed",
      artist: "Wings",
      debutDate: "1977-02-12",
      peak: 10,
      peakDate: "1977-04-02",
      weeksOn: 13,
    },
    {
      title: "Helen Wheels",
      artist: "Paul McCartney And Wings",
      debutDate: "1973-11-24",
      peak: 10,
      peakDate: "1974-01-12",
      weeksOn: 13,
    },
    {
      title: "Hi, Hi, Hi",
      artist: "Wings",
      debutDate: "1972-12-16",
      peak: 10,
      peakDate: "1973-02-03",
      weeksOn: 11,
    },
    {
      title: "Venus And Mars Rock Show",
      artist: "Wings",
      debutDate: "1975-11-01",
      peak: 12,
      peakDate: "1975-12-13",
      weeksOn: 9,
    },
    {
      title: "All Day",
      artist:
        "Kanye West Featuring Theophilus London, Allan Kingdom & Paul McCartney",
      debutDate: "2015-03-21",
      peak: 15,
      peakDate: "2015-03-21",
      weeksOn: 15,
    },
    {
      title: "Getting Closer",
      artist: "Wings",
      debutDate: "1979-06-16",
      peak: 20,
      peakDate: "1979-07-28",
      weeksOn: 10,
    },
    {
      title: "Press",
      artist: "Paul McCartney",
      debutDate: "1986-08-02",
      peak: 21,
      peakDate: "1986-09-13",
      weeksOn: 11,
    },
    {
      title: "Give Ireland Back To The Irish",
      artist: "Wings",
      debutDate: "1972-03-11",
      peak: 21,
      peakDate: "1972-04-08",
      weeksOn: 8,
    },
    {
      title: "So Bad",
      artist: "Paul McCartney",
      debutDate: "1983-12-24",
      peak: 23,
      peakDate: "1984-02-11",
      weeksOn: 14,
    },
    {
      title: "I've Had Enough",
      artist: "Wings",
      debutDate: "1978-06-17",
      peak: 25,
      peakDate: "1978-08-05",
      weeksOn: 11,
    },
    {
      title: "My Brave Face",
      artist: "Paul McCartney",
      debutDate: "1989-05-27",
      peak: 25,
      peakDate: "1989-07-08",
      weeksOn: 10,
    },
    {
      title: "Wonderful Christmastime",
      artist: "Paul McCartney",
      debutDate: "2018-12-29",
      peak: 26,
      peakDate: "2024-01-06",
      weeksOn: 16,
    },
    {
      title: "Mary Had A Little Lamb/Little Woman Love",
      artist: "Wings",
      debutDate: "1972-06-17",
      peak: 28,
      peakDate: "1972-07-22",
      weeksOn: 7,
    },
    {
      title: "Arrow Through Me",
      artist: "Wings",
      debutDate: "1979-08-25",
      peak: 29,
      peakDate: "1979-10-13",
      weeksOn: 10,
    },
    {
      title: "Girls' School",
      artist: "Wings",
      debutDate: "1977-11-19",
      peak: 33,
      peakDate: "1978-01-14",
      weeksOn: 11,
    },
    {
      title: "Only One",
      artist: "Kanye West Featuring Paul McCartney",
      debutDate: "2015-01-17",
      peak: 35,
      peakDate: "2015-01-17",
      weeksOn: 8,
    },
    {
      title: "London Town",
      artist: "Wings",
      debutDate: "1978-09-09",
      peak: 39,
      peakDate: "1978-10-14",
      weeksOn: 8,
    },
    {
      title: "Letting Go",
      artist: "Wings",
      debutDate: "1975-10-04",
      peak: 39,
      peakDate: "1975-10-25",
      weeksOn: 6,
    },
    {
      title: "Sgt. Pepper's Lonely Hearts Club Band",
      artist: "Paul McCartney With U2",
      debutDate: "2005-07-23",
      peak: 48,
      peakDate: "2005-07-23",
      weeksOn: 1,
    },
    {
      title: "Tug Of War",
      artist: "Paul McCartney",
      debutDate: "1982-10-02",
      peak: 53,
      peakDate: "1982-10-23",
      weeksOn: 8,
    },
    {
      title: 'The World Tonight (From "Fathers\' Day")',
      artist: "Paul McCartney",
      debutDate: "1997-05-24",
      peak: 64,
      peakDate: "1997-05-24",
      weeksOn: 10,
    },
    {
      title: "Dance Tonight",
      artist: "Paul McCartney",
      debutDate: "2007-07-07",
      peak: 69,
      peakDate: "2007-07-07",
      weeksOn: 2,
    },
    {
      title: "Stranglehold",
      artist: "Paul McCartney",
      debutDate: "1986-11-15",
      peak: 81,
      peakDate: "1986-11-29",
      weeksOn: 6,
    },
    {
      title: "Hope Of Deliverance",
      artist: "Paul McCartney",
      debutDate: "1993-02-20",
      peak: 83,
      peakDate: "1993-03-13",
      weeksOn: 6,
    },
    {
      title: "Figure Of Eight",
      artist: "Paul McCartney",
      debutDate: "1990-01-13",
      peak: 92,
      peakDate: "1990-01-13",
      weeksOn: 5,
    },
    {
      title: "This One",
      artist: "Paul McCartney",
      debutDate: "1989-09-09",
      peak: 94,
      peakDate: "1989-09-16",
      weeksOn: 3,
    },
    {
      title: "Freedom",
      artist: "Paul McCartney",
      debutDate: "2001-12-15",
      peak: 97,
      peakDate: "2001-12-15",
      weeksOn: 2,
    },
  ],
  artist: "Paul McCartney",
  url: "http://www.billboard.com/artist/Paul-Mccartney/chart-history/hsi/",
  numOnes: 9,
  topTens: 23,
  numSongs: 47,
};
